---
  p12: 'spec/file/privatekey.p12'
  client_email: '877@developer.gserviceaccount.com'
  user_email: 'web@jliquid.ch'
  yaml: 'spec/file/auth.yaml'
  yaml_relative: 'spec/file/auth.yaml'
  bad_yaml: 'spec/file/bad_yaml.yaml'
  calendar_id: 'neville.dubuis@liquid-concept.ch'
